# Generated by Django 6.0.6 on 2026-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('legume', 'Légumes'), ('fruit', 'Fruits'), ('cereale', 'Céréales'), ('forestiers', 'Forestiers')], max_length=20),
        ),
    ]
